title: EEP
description: English Etymology Project
author: Pierre ML

baseurl: /Project-Etymology-graph
url: https://nevaada.github.io

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

exclude: ["Readme.md"]